### ISSUE TITLE
How to generate libsai?

### ISSUE THREAD

**Issue by gck-04** [opencomputeproject/SAI#1162]
Hi all,

I am new to this SONiC build work. And I am trying to generate libsai shared library.
Please help me out with steps to build, as there are no proper steps mentioned in the repo.

Any help would be much appreciated.

Thanks,
gck

**Comment by kcudnik** [comment]
SAI repo contains only C headers. They define what functions sai library should have. If you want to have your own library, you would need to write it from scratch by/for your self. Currently each hardware vendor that supports sonic write it's own library (like broadcom or mellanox), and they support their own hardware.

Sonic already supports couple types of hardware and for them vendors provide binary package with libsai.so.

Please describe what is your goal, and try to start with sonic build image: http://github.com/Azure/sonic-buildimage/

**Comment by gck-04** [comment]
Hi kcudnik,

Thank you for the reply.

I wanted to build this for p4 soft switch, not for the hardware ASIC.
I could find some Makefile in stub/ directory but it is failing.

My goal is to build sai-redis and sai-swss packages independently. Build is failing because they are dependent on libsai. 

Also, if possible please help me understand what is p4-soft switch and what are its components(like how bmv2, p4c are related?)

Thanks,
Gangadhar

**Comment by gck-04** [comment]
> SAI repo contains only C headers. They define what functions sai library should have. If you want to have your own library, you would need to write it from scratch by/for your self. Currently each hardware vendor that supports sonic write it's own library (like broadcom or mellanox), and they support their own hardware.
> 
> Sonic already supports couple types of hardware and for them vendors provide binary package with libsai.so.
> 
> Please describe what is your goal, and try to start with sonic build image: [http://github.com/Azure/sonic-buildimage/](https://github.com/Azure/sonic-buildimage/)

Hi kcudnik,

Thank you for the reply.

I wanted to build this for p4 soft switch, not for the hardware ASIC.
I could find some Makefile in stub/ directory but it is failing.

My goal is to build sai-redis and sai-swss packages independently. Build is failing because they are dependent on libsai.

Also, if possible please help me understand what is p4-soft switch and what are its components(like how bmv2, p4c are related?)

Thanks,
Gangadhar

**Comment by kcudnik** [comment]
Hey, unfortunately i'm  not followine P4 platform, the only implementation one that i could find is here:
https://github.com/Mellanox/SAI-P4-BM/tree/c763924affd416df9c4d3e40d4f8ac1cb2be5fff/sai_adapter/src and in sonic build image https://github.com/Azure/sonic-buildimage/tree/master/platform/p4

as far as im ware you could pass P4 flags to sonic build image to compile for that platform, but git submodule pointing to P4 source is 3 year old, so it definitely not following SAI origin/master, and its most likely out of date

probably would be best to ask some from Mellanox to help here, i will ad @lguohan to help point someone who can help determine status of P4 platform

@lguohan can you help ?

**Comment by gck-04** [comment]
Thank you Kamil.

Hi @lguohan could you please add your thoughts on this?
