### ISSUE TITLE
Remove stub directory?

### ISSUE THREAD

**Issue by kcudnik** [opencomputeproject/SAI#1167]
@itaibaz you added this on the first place, is anyone using stub directory ? not much happened since beginning, and it's based on 0.9.4 branch. Do we still need it ?

**Comment by qiluo-msft** [comment]
We found a potential integer overflow in below code. If stub is obsolete, let's remove this folder completely.
```
stub/src/stub_sai_vlan.c:100:    vlans[0].port_list = malloc(sizeof(sai_vlan_port_t) * PORT_NUMBER);
```

**Comment by itaibaz** [comment]
Hi, yes I think it's obsolete by now. We used it for a while several years ago. But haven't updated it for a very long time, and I don't know of anyone using it. Also, Sonic has the virtual SAI implementation. So bottom line, we can remove

**Comment by qiluo-msft** [comment]
Closed by https://github.com/opencomputeproject/SAI/pull/1168
(I don't have permission to close this issue)
