### ISSUE TITLE
some meta data attributes are incorrect

### ISSUE THREAD

**Issue by itaibaz** [opencomputeproject/SAI#1188]
Hi @kcudnik 

for
.allowrepetitiononlist
.allowmixedobjecttypes
.allowemptylist
Seems they are always false in generated saimetadata.c
Seems no tag exposes them, the only tag we have for allow* is "allownull"
Therefor, the generated metadata is incorrect
For example, let's consider 

    /**
     * @brief Enable/Disable Mirror session
     *
     * Enable ingress mirroring by assigning list of mirror session object id
     * as attribute value, disable ingress mirroring by assigning object_count
     * as 0 in objlist.
     *
     * @type sai_object_list_t
     * @flags CREATE_AND_SET
     * @objects SAI_OBJECT_TYPE_MIRROR_SESSION
     * @default empty
     */
    SAI_PORT_ATTR_INGRESS_MIRROR_SESSION,

The attribute can clearly accept empty list by definition, used for clearing it

However generated metadata is
const sai_attr_metadata_t sai_metadata_attr_SAI_PORT_ATTR_INGRESS_MIRROR_SESSION = {
    .objecttype                    = SAI_OBJECT_TYPE_PORT,
    .attrid                        = SAI_PORT_ATTR_INGRESS_MIRROR_SESSION,
    .attridname                    = "SAI_PORT_ATTR_INGRESS_MIRROR_SESSION",
    .brief                         = "Enable/Disable Mirror session.",
    .attrvaluetype                 = SAI_ATTR_VALUE_TYPE_OBJECT_LIST,
    .flags                         = (sai_attr_flags_t)(SAI_ATTR_FLAGS_CREATE_AND_SET),
    .allowedobjecttypes            = sai_metadata_SAI_PORT_ATTR_INGRESS_MIRROR_SESSION_allowed_objects,
    .allowedobjecttypeslength      = 1,
    .allowrepetitiononlist         = false,
    .allowmixedobjecttypes         = false,
    .allowemptylist                = false,
    .allownullobjectid             = false,
...

so clearly allowemptylist false is incorrect here
Same for SAI_PORT_ATTR_EGRESS_MIRROR_SESSION, and also SAI_PORT_ATTR_EGRESS_BLOCK_PORT_LIST, SAI_PORT_ATTR_QOS_INGRESS_BUFFER_PROFILE_LIST, SAI_PORT_ATTR_QOS_EGRESS_BUFFER_PROFILE_LIST, and others

I believe we might need to extend the infrastructure, by adding 3 tags - allowrepetitiononlist, allowmixedobjecttypes, allowemptylist + fixing header files to have correct values
Or if we think there is no use case at the moment, then remove the attribs from the struct, as now they are incorrect. And add them back in the future with full support if needed

**Comment by kcudnik** [comment]
yes they are always empty at the moment since they are not implemented, are you planning to use them ?

```perl
1670 sub ProcessAllowRepeat
1671 {
1672     my ($attr, $value) = @_;
1673
1674     return "false" if not defined $value;
1675
1676     return $value;
1677 }
1678
1679 sub ProcessAllowMixed
1680 {
1681     my ($attr, $value) = @_;
1682
1683     return "false" if not defined $value;
1684
1685     return $value;
1686 }
1687
1688 sub ProcessAllowEmpty
1689 {
1690     my ($attr, $value) = @_;
1691
1692     return "false" if not defined $value;
1693
1694     return $value;
1695 }
```

**Comment by itaibaz** [comment]
Hi, yes I was planning to use these values, especially the allow empty list
Is there any plan on adding them ? (otherwise, maybe better to comment them out not to confuse)
Thanks

**Comment by kcudnik** [comment]
yes, i can add support for that

**Comment by kcudnik** [comment]
https://github.com/opencomputeproject/SAI/pull/1190
