### ISSUE TITLE
Clarification on Attr SAI_SWITCH_ATTR_MACSEC_OBJECT_ID

### ISSUE THREAD

**Issue by SarathBug** [opencomputeproject/SAI#1196]
https://github.com/opencomputeproject/SAI/blob/1eb35afdb2146baf40e6c2b8f2f8bfe99075eaee/inc/saiswitch.h#L2302

SAI switch can have both ingress and egress MACSec objects(https://github.com/opencomputeproject/SAI/blob/master/inc/saimacsec.h#L60) .  The switch object does not appear to accommodate both MACSec objects

**Comment by lguohan** [comment]
@dipankar-ba , can you clarify?

**Comment by dipankar-ba** [comment]
This is indeed a bug - thanks for finding it.  For fix, I just submitted https://github.com/opencomputeproject/SAI/pull/1199
