### ISSUE TITLE
sai_deserialize_macsec_salt() has incorrect number of parameters parsed

### ISSUE THREAD

**Issue by pony1552** [opencomputeproject/SAI#1241]
macsec_salt is defined as char[12]. sai_deserialize_macsec_salt() parses it as char[32]

**Comment by kcudnik** [comment]
this was changed in commit 60e21080, author @DeanKalla please fix

**Comment by kcudnik** [comment]
fixed here: https://github.com/opencomputeproject/SAI/pull/1311
