### ISSUE TITLE
SAI_SWITCH_STAT_ECC_DROP is not starting at RANGE_BASE

### ISSUE THREAD

**Issue by kcudnik** [opencomputeproject/SAI#1263]
https://github.com/opencomputeproject/SAI/commit/2234327f#diff-8461e6438fb46cfa3d81a0760d680f8e5ac38c57da553a8f9add2fa3ffde3549R2298

should be SAI_SWITCH_STAT_ECC_DROP = SAI_SWITCH_STAT_FABRIC_DROP_REASON_RANGE_BASE

**Comment by kcudnik** [comment]
@michaelli10 can you confirm this is mistake?

**Comment by kcudnik** [comment]
Fix: https://github.com/opencomputeproject/SAI/pull/1264

**Comment by michaelli10** [comment]
> @michaelli10 can you confirm this is mistake?

Yes, thanks for fixing this.

**Comment by kcudnik** [comment]
Fixed and merged
