### ISSUE TITLE
SAI_PORT_ATTR_AUTO_NEG_FEC_MODE_EXTENDED should be moved to READ_ONLY block in SAI PORT

### ISSUE THREAD

**Issue by Pterosaur** [opencomputeproject/SAI#1277]
https://github.com/opencomputeproject/SAI/blob/e38f26b34c25d349dbfd6abbd5fc58f48d720c08/inc/saiport.h#L488

https://github.com/opencomputeproject/SAI/blob/e38f26b34c25d349dbfd6abbd5fc58f48d720c08/inc/saiport.h#L1958-L1966

**Comment by kcudnik** [comment]
its not like there is requirement for that, attributes are added at the end as they are introduced, and sometimes grouped in more meaningful manner rather than flags
