### ISSUE TITLE
Can i skip the judgment in SAI/meta/checksymbols.pl?

### ISSUE THREAD

**Issue by zhuangjh3** [opencomputeproject/SAI#1282]
I am currently supporting gcov in SAI,but it reported an error such as 

ERROR: symbol '000000000000c340 d __gcov_.sai_serialize_udf_group_type' is not prefixed 'sai_metadata_' or not in read-only section
ERROR: symbol '000000000000c380 d __gcov_.sai_serialize_vlan_flood_control_type' is not prefixed 'sai_metadata_' or not in read-only section
ERROR: symbol '000000000000cfc0 d __gcov_.sai_serialize_vlan_list' is not prefixed 'sai_metadata_' or not in read-only section
ERROR: symbol '000000000000c3c0 d __gcov_.sai_serialize_vlan_mcast_lookup_key_type' is not prefixed 'sai_metadata_' or not in read-only section
ERROR: symbol '000000000000c400 d __gcov_.sai_serialize_vlan_stat' is not prefixed 'sai_metadata_' or not in read-only section
ERROR: symbol '000000000000c440 d __gcov_.sai_serialize_vlan_tagging_mode' is not prefixed 'sai_metadata_' or not in read-only section
.....

So I want to know if I can skip the judgment in SAI/meta/checksymbols.pl ？

**Comment by kcudnik** [comment]
you need to add exception for gcov in line 42 if symbol matches

**Comment by kcudnik** [comment]
something like:
```
next if $name =~ /^gcov/;
```

**Comment by kcudnik** [comment]
or add prefix in exitsing one 
```
/^(gcov.)?sai_
```

**Comment by zhuangjh3** [comment]
Thank you, and I would like to ask if the symbol does not start with 'sai_metadata_', what might happen to the program when it is running?

**Comment by kcudnik** [comment]
nothing, its just to make sure that all symbols exported are in this format

**Comment by zhuangjh3** [comment]
I see, thank you！
