### ISSUE TITLE
[meta] Add api type cast for gcc-10 enum conversion complain

### ISSUE THREAD

**Issue by itaibaz** [opencomputeproject/SAI#1312]
https://github.com/opencomputeproject/SAI/pull/1290
Fixes conversion of object type extensions to object type

There are additional error of conversion of extended api type to api type
For example,
meta/saimetadata.c:1464:5: error: implicit conversion from 'enum _sai_api_extensions_t' to 'enum _sai_api_t' [-Werror=enum-conversion]
 1464 |     SAI_API_BMTOR,

**Comment by kcudnik** [comment]
i guess there could be more issues like this for all extensions, i doesn't make sense to cast every api in parser, but maybe workaroud for this would be to add pragma with disable enum-conversion warning, for entire saimetadata.c, @itaibaz what do you think?

**Comment by itaibaz** [comment]
I'm fine with both approaches
Adding the conversion to sai_api_extensions_t to sai_api_t will only need to be done in few places (at least right now)
But it's correct this can grow in the future with few more types, and enum values
So using a pragma can also be a valid approach

**Comment by kcudnik** [comment]
i checked on godbolt.com and there is no flag enum-conversion using gcc 10.3:
```
cc1plus: warning: command-line option '-Wenum-conversion' is valid for C/ObjC but not for C++
```

what exact compiler version are you using to get this enum warnings ?

**Comment by kcudnik** [comment]
Fix: https://github.com/opencomputeproject/SAI/pull/1317
