### ISSUE TITLE
Doxygen build failure on bullseye

### ISSUE THREAD

**Issue by jusherma** [opencomputeproject/SAI#1370]
The bullseye release of Debian uses a new version of doxygen, which seems to be incompatible with the doxygen files under meta/. This can be easily reproduced by trying to build the following Dockerfile:

```Dockerfile
FROM sonicdev-microsoft.azurecr.io:443/sonic-slave-bullseye:latest

RUN wget https://github.com/opencomputeproject/SAI/archive/refs/tags/v1.9.1.tar.gz
RUN tar -xvzf v1.9.1.tar.gz
RUN cd SAI-1.9.1/meta && make
```

This produces a lot of errors like this:

```
/SAI-1.9.1/experimental/saiexperimentalbmtor.h:277: warning: Illegal command \n as part of a title section
/SAI-1.9.1/experimental/saiexperimentalbmtor.h:278: warning: Illegal command @par as part of a title section
/SAI-1.9.1/experimental/saiexperimentalbmtor.h:278: warning: Illegal command \n as part of a title section
/SAI-1.9.1/experimental/saiexperimentalbmtor.h:285: warning: Illegal command \n as part of a title section
/SAI-1.9.1/experimental/saiexperimentalbmtor.h:286: warning: Illegal command @par as part of a title section
```

These errors go away when the Dockerfile is modified to use `sonic-slave-buster:latest` as the base image. 

Please let me know if I'm missing something here

**Comment by kcudnik** [comment]
yes, those versions of doxygen are not compatible it will require change "\\n" in ALIAS to "^^" like this in Doxygen file:
```
ALIASES                += "flags          =@par Flags:\n                  @xmlonly @@flags          @endxmlonly"
to
ALIASES                += "flags          =@par Flags:^^                  @xmlonly @@flags          @endxmlonly"
```

**Comment by jusherma** [comment]
Thanks. After making that change and running `doxygen -u` to auto-update the Doxyfile, the build now progresses past the doxygen stage (and gets stuck at gcc-10 compiler warnings).

I was under the impression that this repo will need to build successfully in a bullseye environment in order for sonic-buildimage to build under bullseye (building `target/debs/bullseye/libsairedis_1.0.0_amd64.deb` fails with the same error right now when it tries to build SAI)

Is my understanding correct?

**Comment by kcudnik** [comment]
not sure about bullseye build, is that using gcc-10 ? what warnings are you seeing there ?

**Comment by jusherma** [comment]
Yeah, gcc-10. Seems like it's more strict than gcc-8 (buster). The warnings seem to be coming from generated code, so I'm not sure how/where to fix it:

```
saimetadatatest.c: In function 'api_name_test':
saimetadatatest.c:2807:73: error: implicit conversion from 'enum _sai_object_type_extensions_t' to 'sai_object_type_t' {aka 'enum _sai_object_type_t'} [-Werror=enum-conversion]
 2807 |         checked[(int)SAI_OBJECT_TYPE_TABLE_BITMAP_CLASSIFICATION_ENTRY] = SAI_OBJECT_TYPE_TABLE_BITMAP_CLASSIFICATION_ENTRY;
      |                                                                         ^
saimetadatatest.c:2827:65: error: implicit conversion from 'enum _sai_object_type_extensions_t' to 'sai_object_type_t' {aka 'enum _sai_object_type_t'} [-Werror=enum-conversion]
 2827 |         checked[(int)SAI_OBJECT_TYPE_TABLE_BITMAP_ROUTER_ENTRY] = SAI_OBJECT_TYPE_TABLE_BITMAP_ROUTER_ENTRY;
      |                                                                 ^
saimetadatatest.c:2847:63: error: implicit conversion from 'enum _sai_object_type_extensions_t' to 'sai_object_type_t' {aka 'enum _sai_object_type_t'} [-Werror=enum-conversion]
 2847 |         checked[(int)SAI_OBJECT_TYPE_TABLE_META_TUNNEL_ENTRY] = SAI_OBJECT_TYPE_TABLE_META_TUNNEL_ENTRY;
      |                                                               ^
cc1: all warnings being treated as errors
```

**Comment by alexrallen** [comment]
@kcudnik We are also facing this issue on SONiC when attempting to upgrade the syncd containers to bullseye. Is there a planned long term solution for this?

**Comment by kcudnik** [comment]
(sai_object_type_t) cast needs to be added explicitly to generated tests, or compiler pragma to ignore enum conversion, this was already done for saimetadata.c

**Comment by alexrallen** [comment]
@kcudnik Apologies, I was referring to the Doxygen issue specifically. Is there a planned fix to allow it to build simultaneously in buster and bullseye? Are we planning to break compatibility with buster? 

I am working on upgrading the NVIDIA syncd container in SONiC right now and we will need SAI to support building within a bullseye environment to complete that work.

**Comment by kcudnik** [comment]
not sure yet how doxygen issue could be fixed, since it require different syntax in file "Doxygen" and if we want to make it work for 2 different doxygen version, then we probably need to Doxygen files, and some logic inside Makefile to support both, and on the fly use correct file, it's tricky since doxygen had breaking change in config

**Comment by alexrallen** [comment]
@kcudnik I believe you may close this issue.
