### ISSUE TITLE
ATTR_PORT_ID in fdb entry MANDATORY_ON_CREATE?

### ISSUE THREAD

**Issue by sonicyao1985** [opencomputeproject/SAI#152]
In saifdb.h, SAI_FDB_ENTRY_ATTR_PORT_ID refers to the dest port/LAG/l2tunnel of the fdb entry, which is marked as MANDATORY_ON_CREATE. If I'm creating a fdb entry with packet action DROP,do I still have to set the SAI_FDB_ENTRY_ATTR_PORT_ID attribute??

**Comment by lguohan** [comment]
the port id MANDATORY only when the packet action needs the port, for example forward, log. If the packet action is DROP, then the port_id is not needed. i'll generate a pull request to clarify this.
