### ISSUE TITLE
[sairpcgen] Extension headers missing from some include paths in Makefile

### ISSUE THREAD

**Issue by chrispsommers** [opencomputeproject/SAI#1531]
When building saithriftv2, extension headers are missing from some include paths, for example see the build run below. I will follow-up with a PR to fix this.
```
ar rcs ./obj/librpcserver.a obj/sai_rpc.o obj/sai_types.o obj/sai_rpc_server.o
g++ -I/usr/include/sai -I. -std=c++11 -O0 -ggdb -c src/saiserver.cpp  -o obj/saiserver.o -I/usr/include/sai -I. -std=c++11 -O0 -ggdb -DBRCMSAI -I./gen-cpp -I../../inc
In file included from /usr/include/sai/sai.h:48,
                 from src/saiserver.cpp:28:
/usr/include/sai/saiobject.h:43:10: fatal error: saiexperimentalbmtor.h: No such file or directory
   43 | #include <saiexperimentalbmtor.h>
```

**Comment by kcudnik** [comment]
probably addressed in here: https://github.com/opencomputeproject/SAI/pull/1533, when experimental directory headers needs to be added to compilation path

**Comment by richardyu-ms** [comment]
cause this issue block the saithrift v2 related docker's build (ptf-sai), try to resolve it here https://github.com/opencomputeproject/SAI/pull/1552/files

**Comment by chrispsommers** [comment]
Hi kind reviewers @kcudnik @richardyu-ms I determined that this issue is bogus, and that copying SAI extension headers to `/usr/include/sai` as explained in [SAI_PTF_user-guide](https://github.com/opencomputeproject/SAI/blob/master/ptf/SAI_PTF_user-guide.md#generate--build) eliminates the problem. I will back out the corresponding changes in https://github.com/opencomputeproject/SAI/pull/1533. Thanks for your advice. - chris
