### ISSUE TITLE
[SAI-PTF] Need to divide the test case according to test objective

### ISSUE THREAD

**Issue by Gfrom2016** [opencomputeproject/SAI#1604]
# Summary
Currently, there are multiple test cases in a class. During the testing process, multiple small test cases in a class are likely to affect each other and cause the test to fail. 

## Details
Take FdbLearnTest class for example, there a two subtest: dynamicMacLearnTest() and macLearnErrorTest(). 
```python
class FdbLearnTest(SaiHelper):
    '''
    Verify different cases of FDB learning
    '''
...
    def runTest(self):
        self.dynamicMacLearnTest()
        self.macLearnErrorTest()
```
## Error message
When we run saifdb.FdbLearnTest, it will run two subtests in turn. We ran into the following error on some platforms.
![image](https://user-images.githubusercontent.com/19384917/191159029-21e20eb9-5ca8-42bb-b9e6-f5864594a2ab.png)

### Another example
Take sairoute.L3RouteTest() as an example. Currently, all 8 subtests are run in sequence at one time. But it failed at the 6th test *sviNeighborTest* which stopped the *cpuForwardTest* and *routeNbrColisionTest* from running.

https://github.com/opencomputeproject/SAI/blob/1b268a820ddb29341f71d1b2f4d6a2444f965bc3/ptf/sairoute.py#L28

```
class L3RouteTest(SaiHelper):
    '''
    Route test class
    '''
    def runTest(self):
        self.multipleRoutesTest()
        self.dropRouteTest()
        self.routeUpdateTest()
        self.routeIngressRifTest()
        self.emptyECMPGroupTest()
        self.sviNeighborTest() <-- failed
        self.cpuForwardTest() <-- not running with result unknown
        self.routeNbrColisionTest() <-- not running with result unknown
```

![image](https://user-images.githubusercontent.com/19384917/195055132-39a91b3e-5b83-4c7c-ba52-ffcaa37e71de.png)

But if we run these test cases separately, *cpuForwardTest* and *routeNbrColisionTest* will all pass like below.
![image](https://user-images.githubusercontent.com/19384917/195055349-71ecab97-7f4f-43e8-b64a-61080e3de95b.png)

![image](https://user-images.githubusercontent.com/19384917/195058275-c0044f99-19e9-4a22-9516-49fd34d79e23.png)

# Proposal
Every test class should only contain one test case that has a clear, simple test objective. Extract each sub-test case from the test class, and continue to split if the sub-test case has multiple test scenarios or objectives. And only config the configuration that the test case required.
## Sample Code or Pull Requests for the proposal
#1602 
#1601

**Comment by richardyu-ms** [comment]
@ravi861 could you help check this issue
