### ISSUE TITLE
[SAI-PTF] Ordering the create/delete api calling sequence - nhop and neighbor

### ISSUE THREAD

**Issue by zhoudongxu** [opencomputeproject/SAI#1607]
**Summary**

   If object A have dependence on  object B, Creating A before B is necessary in some platform. If object A have dependence on object B, Deleting A after B is necessary

**Details** 
   For example, Creating object must be in order neighbor->nexthop->route, otherwise, it will failed. Below code will fail in other platform because creating nhop  is before creating neighbor, however nhop have dependence on neighbor

``

        print("RemoveNexthopTest")
        nhop = sai_thrift_create_next_hop(self.client,
                                          ip=sai_ipaddress('10.10.10.10'),
                                          router_interface_id=self.port10_rif,
                                          type=SAI_NEXT_HOP_TYPE_IP)
        neighbor_entry = sai_thrift_neighbor_entry_t(
            rif_id=self.port10_rif, ip_address=sai_ipaddress('10.10.10.10'))
        sai_thrift_create_neighbor_entry(self.client, neighbor_entry,
                                         dst_mac_address='00:99:99:99:99:99')

        route1 = sai_thrift_route_entry_t(
            vr_id=self.default_vrf, destination=sai_ipprefix('10.10.10.2/32'))
        sai_thrift_create_route_entry(self.client, route1, next_hop_id=nhop)

``

 Below code  also will fail in other platform because deleting nhop  is after creating neighbor, however nhop have dependence on neighbor
``

            sai_thrift_remove_route_entry(self.client, route1)
            sai_thrift_remove_neighbor_entry(self.client, neighbor_entry)
            sai_thrift_remove_next_hop(self.client, nhop)

``

**Error message**
![image](https://user-images.githubusercontent.com/22717106/191186117-30d4c4f8-3dc5-4e9c-a536-aa783f3b2b04.png)

**Proposal**
Ordering the calling sequence,   If object A have dependence on  object B, Creating A before B is necessary in some platform. If object A have dependence on object B, Deleting A after B is necessary

**Sample Code or Pull Requests for the proposal**
[1599](https://github.com/opencomputeproject/SAI/pull/1599/files)

**Comment by richardyu-ms** [comment]
@ravi861 could you help check this issue

**Comment by richardyu-ms** [comment]
fixed in #1677 and #1632
