### ISSUE TITLE
[SAI-PTF] sai_thrift_get_xxx_stats function enhancement

### ISSUE THREAD

**Issue by zhoudongxu** [opencomputeproject/SAI#1613]
**Summary**
 We  need a new getting stats function which passes a specific counter id as parameter  such as SAI_PORT_STAT_IF_IN_UCAST_PKTS

**Details** 
   For example, we must  get all  counters of a port  firstly if  just needing to get  SAI_PORT_STAT_IF_IN_UCAST_PKTS counter.
   There are some problems maybe at this point.   Some vendor will return SAI_PORT_STAT_IF_IN_UCAST_PKTS  counter value as 0  if  querying other kind of counter ahead of SAI_PORT_STAT_IF_IN_UCAST_PKTS  fails 

``

      post_port_stats = sai_thrift_get_port_stats(self.client, self.port1_oid)

      self.assertEqual(post_port_stats["SAI_PORT_STAT_IF_IN_UCAST_PKTS"]- pre_port_stats["SAI_PORT_STAT_IF_IN_UCAST_PKTS"], 1)

``

**Proposal** 
Please provide a new function which only return  the counter specified by counter_d parameter
 sai_thrift_get_port_stats(self.client, self.port1_oid, counter_id)

**Comment by richardyu-ms** [comment]
duplicated with https://github.com/opencomputeproject/SAI/issues/1614
