### ISSUE TITLE
[SAI-PTF] Wrong mac address representation in test case

### ISSUE THREAD

**Issue by Gfrom2016** [opencomputeproject/SAI#1619]
# Summary
There are several wrong mac addresses in the ptf test case where mac addresses are 56-bit instead of 48-bit. Need to change them to the correct format.

# Error detail
In some test cases, there are wrong mac address representations, like the one below.
https://github.com/opencomputeproject/SAI/blob/1b268a820ddb29341f71d1b2f4d6a2444f965bc3/ptf/saivlan.py#L63

# Proposal
Change the wrong mac address to the correct format which should be 48-bit.

## Sample Code or Pull Requests for the proposal
#1601

**Comment by richardyu-ms** [comment]
@ravi861, please help to check this issue, any suggestion are welcome.

thanks.

**Comment by richardyu-ms** [comment]
fixed in #1677
