### ISSUE TITLE
Updates to basic_router.cpp

### ISSUE THREAD

**Issue by shaharg3465** [opencomputeproject/SAI#174]
I have an update for basic_router.cpp to work with the new SAI APIs for VLANs.
How can I send the changes?

**Comment by stcheng** [comment]
@shaharg3465 You could create a pull request against the current master for code review.

**Comment by shaharg3465** [comment]
I probably don't have the right permissions to do it or my procedure is wrong.
can you help with the right flow?

**Comment by lguohan** [comment]
merged https://github.com/opencomputeproject/SAI/pull/176
