### ISSUE TITLE
wrong size of sai_acl_capability_t

### ISSUE THREAD

**Issue by oplklum** [opencomputeproject/SAI#1922]
Dear expects,
When I make SAI meta code, a sizeof assert error is reported. The value SAI_ACL_CAPABILITY_T_SIZE generated by script is 24, but sizeof(sai_acl_capability_t) is 32. Why this happened? Please give me some suggestion, thank you.

In saimetadatasize.h:
#define SAI_ACL_CAPABILITY_T_SIZE (24)

The log is shown below:

GEN_SAIRPC_OPTS="-ve" make

GNU Make 4.2.1
gcc (Ubuntu 10.5.0-1ubuntu1~20.04) 10.5.0
This is perl 5, version 30, subversion 0 (v5.30.0) built for x86_64-linux-gnu-thread-multi
@(#) International Ispell Version 3.1.20 (but really Aspell 0.60.8)
dot - graphviz version 2.43.0 (0)
doxygen: 1.8.17
GNU nm (GNU Binutils for Ubuntu) 2.34
doxygen Doxyfile 2>&1 | perl -npe '$e=1 if /warning/i; END{exit $e}'
touch xml
perl -I. parse.pl
Processing capability file sample.cap
Skipping cap file sample.cap
...
processing commit f981a1f
processing commit 16e5050
processing commit b4331a0
./saimetadatatest >/dev/null
struct/union sai_twamp_session_stats_data_t not defined in base branch, skipping size check
struct/union sai_twamp_session_event_notification_data_t not defined in base branch, skipping size check
struct/union sai_ip_prefix_list_t not defined in base branch, skipping size check
struct/union sai_acl_chain_t not defined in base branch, skipping size check
struct/union sai_acl_chain_list_t not defined in base branch, skipping size check
**ASSERT TRUE FAILED(4916): sizeof(sai_acl_capability_t) == (SAI_ACL_CAPABILITY_T_SIZE): wrong size of sai_acl_capability_t, expected 24, got 32**
make: *** [Makefile:92: all] Error 1

**Comment by kcudnik** [comment]
Did you make any changes to it? Previous vsle US generated Frombork master commit  and cslculated by the same compiler, so it seems live you made some changes, domyounhave pr?

**Comment by kcudnik** [comment]
Ji think you are not building this on master branch and on you branch there is No cherry picked chane that updated capability struct

**Comment by oplklum** [comment]
> Ji think you are not building this on master branch and on you branch there is No cherry picked chane that updated capability struct

Yes, I found the issues, I have not switch to master, the code was not updated.
Thanks for your help. This issue could be closed.
