### ISSUE TITLE
outside the range of type ‘sai_object_type_t’

### ISSUE THREAD

**Issue by oplklum** [opencomputeproject/SAI#1925]
I add 5 new objects in experimental, so the SAI_OBJECT_TYPE_EXTENSIONS_MAX is increased from 124 to 129. But when I make meta, an error reported like this:

In file included from saidepgraphgen.cpp:33:
saidepgraphgen.cpp: In function ‘void process_colors()’:
saimetadata.h:489:60: error: the result of the conversion is unspecified because ‘129’ is outside the range of type ‘sai_object_type_t’ {aka ‘_sai_object_type_t’} [-Werror=conversion]
  489 | #define SAI_OBJECT_TYPE_EXTENSIONS_MAX ((sai_object_type_t)129)

I think it's the reason of enum underlying type is not fixed, so it'll be all right when SAI_OBJECT_TYPE_EXTENSIONS_MAX <= 127, otherwise conversion outside the range. I change the value to 127 manually and it works, but report error [-Werror=conversion] when change to 128. So is this a bug?

**Comment by kcudnik** [comment]
yes, probably a bug, can you give link to commit? i will pull that locally and fix that

**Comment by oplklum** [comment]
> yes, probably a bug, can you give link to commit? i will pull that locally and fix that

I've commit my code to https://github.com/oplklum/SAI/commit/54c18db9490b5f1c5f9200c9a31e5c05581296e2
Please have a test, thanks.

**Comment by kcudnik** [comment]
thanks, i cherry picked that, seems like gcc compiler internally chooses some 7 bit size to store enum values for sai_object_type_t, even that sizeof(sai_object_type_t) is sizeof(int32_t), and error pops up on cpp, not C, i'm not sure how to elegantly fix this, i can add pragam to ignore this conversion, but im not sure if this could have some implications later, if at some point compiler will decide to actual 7 bits, at some operations

**Comment by kcudnik** [comment]
i tried to add
```
#pragma GCC diagnostic ignored "-Wconversion"
```

but seems like gcc is ignoring this pragma, since warning is still present if that pragma is applied, not sure if this is gcc bug or a feature

**Comment by kcudnik** [comment]
@oplklum i added temporary workaround: https://github.com/opencomputeproject/SAI/pull/1926, you can cherrypick that and try to build and test locally, but we need to discuss this change on Thursday SAI community meeting

**Comment by oplklum** [comment]
@kcudnik I'm sorry for the late response. #1925 is all right now, but the same problem happened for sai_api_t.

#define SAI_API_EXTENSIONS_MAX ((sai_api_t)69) 

I guess the actual bits is 6, so when it's > 64, an same error reported. I add custom range as below for temporary pass. Please know.

    SAI_API_MAX,                   /**< total number of APIs */
    SAI_API_CUSTOM_RANGE_START = 256,
    SAI_API_CUSTOM_RANGE_END
} sai_api_t;

**Comment by kcudnik** [comment]
ok, i will update that

**Comment by kcudnik** [comment]
i already merged that on master for object_type and api, so you can build on that
