### ISSUE TITLE
SAI_TUNNEL_ATTR_ENCAP_GRE_KEY_VALID should be removed

### ISSUE THREAD

**Issue by kcudnik** [opencomputeproject/SAI#199]
/*\* tunnel GRE key valid [bool](CREATE_ONLY) (default = false)
     \*  (valid only when SAI_TUNNEL_ATTR_TYPE = SAI_TUNNEL_IPINIP_GRE) */
    SAI_TUNNEL_ATTR_ENCAP_GRE_KEY_VALID,

   /*\* tunnel GRE key [sai_uint32_t](MANDATORY_ON_CREATE when
     *  SAI_TUNNEL_ATTR_ENCAP_GRE_KEY_VALID=true) (CREATE_ONLY) */
    SAI_TUNNEL_ATTR_ENCAP_GRE_KEY,

SAI_TUNNEL_ATTR_ENCAP_GRE_KEY should be mandatory on create when SAI_TUNNEL_ATTR_TYPE = SAI_TUNNEL_IPINIP_GRE, there is no need for extra *_VALID attribute

**Comment by lguohan** [comment]
for IP in IP gre tunneling, gre key is an optional field. see rfc2890

2. Extensions to GRE Header

   The GRE packet header[1] has the following format:

     ```
0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
    |C|       Reserved0       | Ver |         Protocol Type         |
    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
    |      Checksum (optional)      |       Reserved1 (Optional)    |
    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+

   The proposed GRE header will have the following format:

    0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |C| |K|S| Reserved0       | Ver |         Protocol Type         |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |      Checksum (optional)      |       Reserved1 (Optional)    |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |                         Key (optional)                        |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |                 Sequence Number (Optional)                    |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+

```

**Comment by kcudnik** [comment]
Then this is "stacked" attribute dependency SAI_TUNNEL_ATTR_ENCAP_GRE_KEY_VALID depend on SAI_TUNNEL_ATTR_TYPE and SAI_TUNNEL_ATTR_ENCAP_GRE_KEY_VALID depend on SAI_TUNNEL_ATTR_ENCAP_GRE_KEY_VALID

In the GRE header if K flag is set to zero, does it mean that Key field is not sent over channel? and after Reserved1 comes Sequence Number? or Key also passes but it's value is unspecified ?
