### ISSUE TITLE
wrong type for SAI_HA_SCOPE_ATTR_HA_SET_ID

### ISSUE THREAD

**Issue by rupeshknvidia** [opencomputeproject/SAI#2057]
Attribute SAI_HA_SCOPE_ATTR_HA_SET_ID should be    * @type sai_object_id_t , and not      * @type sai_uint16_t

/**
 * @brief Attribute ID for HA scope
 */
typedef enum _sai_ha_scope_attr_t
{
...

    /**
     * @brief Action parameter HA set id
     *
     * @type sai_uint16_t
     * @flags CREATE_AND_SET
     * @isvlan true
     * @default 0
     */
    SAI_HA_SCOPE_ATTR_HA_SET_ID = SAI_HA_SCOPE_ATTR_START,

**Comment by KrisNey-MSFT** [comment]
The auto-gen code missed this and put regular scalar.  Object type is here:  

[see here HA SET ID Attribute ]([SAI/experimental/saitypesextensions.h at master · opencomputeproject/SAI (github.com)](https://github.com/opencomputeproject/SAI/blob/master/experimental/saitypesextensions.h#L73))

**Comment by KrisNey-MSFT** [comment]
Close Issue after PR is merged.
