### ISSUE TITLE
L3MultipleEcmpLagTest

### ISSUE THREAD

**Issue by lguohan** [opencomputeproject/SAI#232]
- Create virtual router
- Reserve port[0] for sending packet. Create a router interface for port[0]
- Test following ECMP and LAG combination:
  - ((n-1)x1 + 1xm), where m = [2, ..., k+1-n], and n is from [2, ...,15]
    where n is the number of members in the ecmp group, and k is the total number of ports, e.g, 16 ports.
- For each combination, using follow steps to test
  - create n-1 router interfaces on each of the (n-1) ports
  - create 1 LAG where the LAG contains m ports, create 1 router interface on top of the LAG
  - create 1 ecmp group that contains n router interfaces
  - send traffic from port[0] to the ecmp group and verify the traffic is balanced among the n router interface, then verify the traffic is balanced among m ports in the LAG

**Comment by engdorm** [comment]
not sure what's 'm' represent; is it the number of ports with Rifs connectivity ? 
and I think that 'n' is the number of next hops in the ecmp group (and there's only one),
because you wrote : " n is from [2, ...,15] where n is the number of ecmp groups"
but then you also wrote : "create 1 ecmp group that contains n router interfaces"

so if I understand it correctly in pseudo code :

create a virtual router 
port[0] connected to router with rif port
make new lag that is connected to router with lag rif
for number_lag_members  range(2,15):
      for i in range(1,number_lag_members): add port[i] to lag
      for i in range(number_lag_members,15): connect port[i] to router with rif port
      create neighbors for all of the rifs
      make a new ecmp group with all the of the rifs except port[0]
      make a new route that passes all of the traffic to the ecmp group
      send traffic
      check balance in the lag, and sum all of the traffic
      check balance in all of the port rifs and compare with the sum of all of the packets from the lag
      destroy route, ecmp group, neighbors, port rifs (except port[0])

**Comment by engdorm** [comment]
`create a virtual router 
port[0] connected to router with rif port
make new lag that is connected to router with lag rif
for number_lag_members range(2,15):
    for i in range(1,number_lag_members): add port[i] to lag
    for i in range(number_lag_members,15): connect port[i] to router with rif port
    create neighbors for all of the rifs
    make a new ecmp group with all the of the rifs except port[0]
    make a new route that passes all of the traffic to the ecmp group
    send traffic
    check balance in the lag, and sum all of the traffic
    check balance in all of the port rifs and compare with the sum of all of the packets from the lag
    destroy route, ecmp group, neighbors, port rifs (except port[0])`

**Comment by lguohan** [comment]
you are right "n is the number of members in the ecmp group" (corrected)

**Comment by kcudnik** [comment]
Resolved in #291
