### ISSUE TITLE
Bind list attrib type change for disable flow.

### ISSUE THREAD

**Issue by tushar-ty** [opencomputeproject/SAI#412]
For the following bind unbind mechanism (same for port, router intf, etc): 

---------------------------------
/**
     * @brief LAG bind point for ingress ACL object
     *
     * Bind (or unbind) an ingress acl table or acl group on a LAG. Enable/Update
     * ingress ACL table or ACL group filtering by assigning the list of valid
     * object id. Disable ingress filtering by assigning SAI_NULL_OBJECT_ID
     * in the attribute value.
     *
     * @type sai_object_list_t
     * @objects SAI_OBJECT_TYPE_ACL_TABLE, SAI_OBJECT_TYPE_ACL_TABLE_GROUP
     * @flags CREATE_AND_SET
     * @allownull true
     * @default SAI_NULL_OBJECT_ID
     */
    SAI_LAG_ATTR_INGRESS_ACL,
---------------------------------

Could we define a slightly different attrib type which contains  a bool 'enable/disable' field along with count and object items. Otherwise we are imposing complication in the SAI adapter implementation for the disable sequence by only passing the NULL object and then in the implementation we need to maintain some kind of association of what all ACLs bind this lag/port/intf etc. and then we need to traverse, search update all effected entries. The application would anyways have this association info as it passed the object list while binding, so it can pass the same list again and mention 'disable/unbind', thereby simplifying the adapter implementation ?

We just need a new attrib type:

typedef struct _sai_acl_bind_list_t {
    booldata enable; /* TRUE/FALSE */
    sai_object_id_t *list;
    uint32_t count;
} sai_acl_bind_list_t;

**Comment by kcudnik** [comment]
This would require adding new attribute value type, which i'm fine with since this object will contain only object id's it will be easy to track dependencies on that

**Comment by lguohan** [comment]
I am fine with it, except for the fact we have changed the acl_bind_list in the master to acl_table, or acl_table_group.
