### ISSUE TITLE
Setting actual count for overflow in the called routine.

### ISSUE THREAD

**Issue by tushar-ty** [opencomputeproject/SAI#518]
Is the following mechanism accurate ? 
"the callee will set the count"
i.e will it work while the address of the count is not passed to the called routine..

Maybe an example showing the working mechanism would help.

/**
 * @brief Defines a list of SAI object ids used as SAI attribute value.
 *
 * In set attribute function call, the count member defines the number of
 * objects.
 *
 * In get attribute function call, the function call returns a list of objects
 * to the caller in the list member. The caller is responsible for allocating the
 * buffer for the list member and set the count member to the size of allocated object
 * list. If the size is large enough to accommodate the list of object id, the
 * callee will then fill the list member and set the count member to the actual
 * number of objects. If the list size is not large enough, the callee will set the
 * count member to the actual number of object id and return
 * #SAI_STATUS_BUFFER_OVERFLOW. Once the caller gets such return code, it should
 * use the returned count member to re-allocate list and retry.
 */
typedef struct _sai_object_list_t {
    uint32_t count;
    sai_object_id_t *list;
} sai_object_list_t;

**Comment by kcudnik** [comment]
Yes, if caller call GET api for getting object list, and specifies count = 20, and allocate buffer for 20 objects, but actually there is 15 objects, callee will populate 15 objects on list and set count to 15, so caller can know what actual count of object is since he overshoot count.
