### ISSUE TITLE
About warmboot

### ISSUE THREAD

**Issue by sonicyao1985** [opencomputeproject/SAI#53]
It is written in the document that this doc deals with restart and upgrade without impacting data plane. So the switching CHIP will not be reset, while NPU SDK might get re-initialized??

**Comment by lguohan** [comment]
That's one implementation approach, a common one. Some chip might support partial reconfiguration without hitting the data plane, that might be another approach.

**Comment by zubinshah** [comment]
@lguohan @sonicyao1985 how do you control or quantify this partial reconfiguration ? should we or do we want to explicitly mention the expected behavior for this case .

**Comment by atitjain** [comment]
@AnbalaganNatchimuthu Please help me understand following from the warmboot proposal:

1. It seems the boot type flag is sent as part of the shutdown_switch API and not from the initialize_switch API. So is adapter supposed to remember this parameter. Typically this is system/platform/application code that should be reading the bootflags. The bootflags are set during shutdown or even as part of signal handler for a segfault etc. I think it should be passed to SAI from initialize call.
2. initiate_switch in the doc should be replaced by initialize_switch
3. Following description is not clear and the comments contradict
    <pre><code>
/\* READ_ONLY \*/
   /\* Minimum interval of time required by SAI for planned restart [sai_uint32_t]
    in milliseconds. Will be 0 for SAI_RESTART_TYPE_NONE \*/
   /\* The Host Adapter will have to wait for this minimum interval of time before it decides
      to bring down SAI due to init failure. \*/
    SAI_SWITCH_ATTR_MIN_PLANNED_RESTART_INTERVAL,
</code></pre>  
Which of the two comments is valid. In the second comment. Is it only related to init failure, do you mean once the Host Adapter gets a init failure it should wait for this interval. 
4. Please let me know why we have 2 files, shouldnt it be a common file for maintaining and recovering state? Rather in a more generic sense the NV could be something that could be completely abstracted from the user. The file format etc might be very different for each of the SDK implementation. In most ideal case the read/write/open etc should be abstracted from a OS abstraction layer.
 <pre><code>
   /\* The file to recover SAI/NPU state from \*/
   #define SAI_KEY_WARM_BOOT_READ_FILE “SAI_WARM_BOOT_READ_FILE”
   /\* The file to write SAI/NPU state to \*/
   #define SAI_KEY_WARM_BOOT_WRITE_FILE “SAI_WARM_BOOT_WRITE_FILE”
</code></pre>  
5. In the following code
  <pre><code>
/\* The NV storage is full. (rv for shutdown_switch()) \*/
SAI_STATUS_NV_STORAGE_FULL                    SAI_STATUS_CODE(0x00000015L)
</code></pre>
Why is this coupled with the shutdown alone. The state sync is ongoing activity.

**Comment by AnbalaganNatchimuthu** [comment]
Dell - Internal Use - Confidential
Hi,


1.      The shutdown_switch API is not taking the boot_type flag. The shutdown_switch API is used to trigger a planned restart. Once this trigger reaches SAI,  SAI would dump its contents to NV store and the also trigger the NPU to dump its contents to NV Store and enter restart. The bootflags indicating the type of boot (either warm or cold) are read from the key value pair before calling the initialize_switch API.



2.      I will correct the document for initiate_switch





3.      The minimum restart interval is the time required by SAI and NPU to store its contents to the NV store on receiving a trigger to do a restart from the Host Adapter. If time taken exceeds this minimum interval then the Host Adapter can take a decision  on bringing down SAI. I will update the document on this section.



4.      Regarding the usage of files for storage, it was decided in the OCP technical committee  to go with files for now and abstract it later with function pointers. Shankara and Gouhan can provide more details on this.



5.      The state sync can be either one time or periodic based on the restart type the NPU supports. I will update the document.

Thanks
Anbalagan

**Comment by atitjain** [comment]
Why not pass the boot-flag things from the system side (infrastructure and other things around the host adapter) to the SAI swith init API, this makes things simpler for various implementations.
