### ISSUE TITLE
Metadata for ACL USER_DEFINED_FIELD group of attributes

### ISSUE THREAD

**Issue by yakivh** [opencomputeproject/SAI#542]
@kcudnik can you please consider adding a metadata for the following attributes:
SAI_ACL_TABLE_ATTR_USER_DEFINED_FIELD_GROUP_MIN
SAI_ACL_TABLE_ATTR_USER_DEFINED_FIELD_GROUP_MAX
SAI_ACL_ENTRY_ATTR_USER_DEFINED_FIELD_MIN
SAI_ACL_ENTRY_ATTR_USER_DEFINED_FIELD_MAX

Thanks

**Comment by kcudnik** [comment]
Can you generate PR for that? Since i don't know what metadata should look like for those

**Comment by kcudnik** [comment]
Take look at PR #636

**Comment by kcudnik** [comment]
Closing this since auto generation was added
