### ISSUE TITLE
saiport.h has controversial api for set/get attribute(s)

### ISSUE THREAD

**Issue by aspirine92** [opencomputeproject/SAI#642]
Current implementation of set and get functions are different. Set works only with one attribute, but get can parse list of attributes.
See code below(saiport.h):
**get**
```
typedef sai_status_t (*sai_get_port_attribute_fn)(
        _In_ sai_object_id_t port_id,
        _In_ uint32_t attr_count,
_Inout_ sai_attribute_t *attr_list);
```
**set**
```
typedef sai_status_t (*sai_set_port_attribute_fn)(
        _In_ sai_object_id_t port_id,
_In_ const sai_attribute_t *attr);
```
Solution: need to change set function in sync with get function

**Comment by lguohan** [comment]
to avoid complex failure handling behavior (in case you set multiple attributes but one of them has failure), the set api (all set APIs) can only set one attribute.

**Comment by aspirine92** [comment]
I'd expect to see 4 different functions:
```
setAttribute
setAttributesList
getAttribute
getAttributesList
```
Let the SAI user to choose how to set/get attribute(s)

**Comment by kcudnik** [comment]
There is no need for get "list" since current get function can get 1 or n attributes at once. As for set, as @lguohan said, it's by design to support only 1 attribute on set. Also if you need set with multiple attributes it's easy for user to implement that and handle failures in the way user want.

Can you give a valid example when setting more attributes at one have more benefits/advantage than setting them one after another ?

**Comment by aspirine92** [comment]
ok, Ex.
I want to set 5 attributes and I need to check each one step by step. I just want to check if value is set correctly.

```

int i;
sai_object_id *attr_ids = (sai_object_id*) calloc(5 * sizeof(sai_object_id));
uint32_t *attr_values = (uint32_t*) calloc(5 * sizeof(uint32_t));
sai_object_id_t port_id;
sai_attribute_t attr;

memset(&port_id, 0, sizeof (port_id));
memset(&attr, 0, sizeof (attr));

//Let`s set some values to these arrays.
for (i = 0; i < 5; ++i)
{
attr_ids = i;
attr_values = i;
}

for (i = 0; i < 5; ++i)
{
//Setting one attribute
    attr.id = attr_ids[i];
    attr.value.u32 = attr_values[i];
    err = sai_set_port_attribute (port_id, attr);
    if (err) printf("Error %i\n", i);

//Resetting attr value
    attr.value.u32  = 0;

//Getting one attribute with a hardcoded attr_count to 1,
// because I need to check only one current value. Isn`t it confusing?
// Also take a look on this function name - "get_port_attribute",
// assuming to work only with one attribute.
    err = sai_get_port_attribute(port_id, 1, &attr);
    if (err) printf("Error %i\n", i);

//Checking value of the current attribute
    if (attr.value.u32 != attr_values[i]) printf("Error value is wrong! %i\n", i); 
}
free(attr_values);
free(attr_ids);
```

**Comment by aspirine92** [comment]
In case of setting list of attributes in a function, one advantage is to check if this function will return no error. So I`m expecting that all the values are set correctly. But there is no such API in SAI, user needs to make it, create some loop and call set function step by step.

**Comment by kcudnik** [comment]
This is fine when all attributtes will be set succesfully, but when one of them fails then behaviou can be ether fail right away and not set other attributes or continue set, but when continuing, more attributes can fail. So setting 1 attribute give user control on what he wants to do in case of failure. I think i dont fully understand your example
