### ISSUE TITLE
Need to pick the "Add doxygen aliases isvlan and validonly" commit from 1.0 to 1.2 as well

### ISSUE THREAD

**Issue by vitaliy-senchyshyn** [opencomputeproject/SAI#715]
@lguohan @kcudnik Could you please pick this commit: https://github.com/opencomputeproject/SAI/commit/e6d1d41294875a020ecfe78d8db5e9d9fc50f081 from 1.0 to 1.2 as well?

**Comment by kcudnik** [comment]
i will fix that

**Comment by kcudnik** [comment]
fixed in #716
