### ISSUE TITLE
QoS Map reset the previous state

### ISSUE THREAD

**Issue by aspirine92** [opencomputeproject/SAI#823]
Hi, 

Just faced with an QoS Map implementation artifacts.

Once we apply QoS Map with the several items, is that expected to reset the previous mapping for the rest available items in Switch before SET operation?

Example:

Create QoS Map 1, Dot1P (PCP or Vlan priority) -> TC [0->1, 1->2]
Create QoS Map 2, Dot1P (PCP or Vlan priority) -> TC [2->3, 3->4]
Apply  QoS Map 1 on the Port 1.
Apply QoS Map 2 on the Port 1.

Which mapping is now saved on the Port 1???

[**0->1, 1->2, 2->3, 3->4**, 4->0, 5->0, 6->0, 7->0]
OR
[0->0, 1->0, **2->3, 3->4**, 4->0, 5->0, 6->0, 7->0]

Thanks

**Comment by AshokDaparthi** [comment]
Hi,

Since you applied on port1 with Map2, Values should be below.
[0->0, 1->0, 2->3, 3->4, 4->0, 5->0, 6->0, 7->0]

Regards
Ashok D

**Comment by aspirine92** [comment]
Hi @AshokDaparthi ,

Thanks for a quick response, it helped a lot!

**Comment by aspirine92** [comment]
Hi,

Just one additional scenario to be clear:

_Example 2._ 

_Create QoS Map 1, Dot1P (PCP or Vlan priority) -> TC [0->1, 1->2] (CREATE operation)
Apply QoS Map 1 on the Port 1. (SET operation)
Change QoS Map 1, Dot1P (PCP or Vlan priority) -> TC [2->3, 3->4] (SET operation)_

Should we retrieve the same mapping as below?
[0->0, 1->0, **2->3, 3->4**, 4->0, 5->0, 6->0, 7->0]

Thanks

**Comment by aspirine92** [comment]
Reopening since one more case needs to be cleared..

**Comment by AshokDaparthi** [comment]
Set is expected to appended list.

**Comment by aspirine92** [comment]
Hi @AshokDaparthi ,

Ok, I see. So how it should handle duplications in old and new list? It`s very complicated implementation as per SAI wrapper...

So at least there is no info about the designed behavior of SAI_QOS_MAP_ATTR_MAP_TO_VALUE_LIST. We should explain to the end-point users what happens under the SET operation here..

Thanks

**Comment by aspirine92** [comment]
Hi @AshokDaparthi,

I have another question according to SAI_QOS_MAP_ATTR_MAP_TO_VALUE_LIST as appending list.
How can we clear the already configured mapping?

Thanks
