### ISSUE TITLE
How to load LED FW of TH3/TD3 in SAI3.5.2.1 from 201904 branch

### ISSUE THREAD

**Issue by tiantianlv** [opencomputeproject/SAI#992]
Hi

In ourselves SAI, we will modify the platform initialization sequence to load port led FW for TH3/TD3, add load in src/brcm-sai-odp/os/platform/x86-xgs5-deb80/platform_init.c::common_init_commands[]: 

  "m0 load 0 0x0 /usr/share/sonic/platform/linkscan_fw.bin",
  "m0 load 0 0x3800 /usr/share/sonic/platform/custom.bin",

In SAI3.5.2.1 from 201904 branch, how to load the LED firmware in SAI initialization for TH3/TD3?

Thanks,
Bo

**Comment by lguohan** [comment]
sonic question.
